### ISSUE TITLE
:bug: Cannot watch for corev1.LimitRange resources

### ISSUE THREAD

**Issue by prometherion** [kubernetes-sigs/controller-runtime#1044]
I'm using Controller Runtime (v0.6.0) scaffolded by Operator SDK (v0.18.1) and I'm not able to get notified once owner referenced `LimitRange` resources are modified.

## More context

```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

```
func add(mgr manager.Manager, r reconcile.Reconciler) error {
	c, _ := controller.New("my-controller", mgr, controller.Options{Reconciler: r})

	err = c.Watch(&source.Kind{Type: &corev1.LimitRange{}}, &handler.EnqueueRequestForOwner{
		IsController: true,
		OwnerType:    &mypkg.MyCrd{},
	})
	if err != nil {
		return err
	}
}
```

Once running up the Operator/Controller, I got the `LimitRange` correctly created/updated.

```yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: redacted
  namespace: redacted
spec:
  limits:
  - max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 50m
      memory: 5Mi
    type: Pod
  - default:
      cpu: 200m
      memory: 100Mi
    defaultRequest:
      cpu: 100m
      memory: 10Mi
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 50m
      memory: 5Mi
    type: Container
  - max:
      storage: 10Gi
    min:
      storage: 1Gi
    type: PersistentVolumeClaim
```

But, after editing it via `kubectl`, I don't get informed about the change, so unable to ensure the desired state is aligned to the actual one.

The CRDs is managing other kinds of resources as:
- `rbacv1.RoleBinding`
- `corev1.ResourceQuota`
- `networkingv1.NetworkPolicy`

All of these are correctly watched, so getting notified to perform the reconciliation loop: that's the reason for guessing a sort of bug or something similar.
