### ISSUE TITLE
envtest: no matches for kind "Infrastructure" in version "config.openshift.io/v1"

### ISSUE THREAD

**Issue by gee4vee** [kubernetes-sigs/controller-runtime#1191]
Dependency versions:
`sigs.k8s.io/controller-runtime v0.6.3`
`github.com/openshift/api v0.0.0-20200326152221-912866ddb162`

I'm getting the error above in my test even though I've added the relevant schema like so:

```
...
	configv1 "github.com/openshift/api/config/v1"
...
var _ = BeforeSuite(func(done Done) {
...
	err = configv1.AddToScheme(scheme.Scheme)
	Expect(err).NotTo(HaveOccurred())
...
```

I have some other schemas I've added including the one for our CRD, and those don't give me problems. The controller does start and begins reconciling our CRD. I also checked the version of the OpenShift API that I'm using to make sure it has `Infrastructure` and it does: https://pkg.go.dev/github.com/openshift/api@v0.0.0-20200623075207-eb651a5bb0ad/config/v1

Am I missing something else? Full code is here: https://github.com/IBM/starter-kit-operator/blob/operator-sdk-upgrade/controllers/suite_test.go

**Comment by ktravis** [comment]
I was also facing this issue without much indication what the problem was - I think I've just realized the problem, maybe someone can correct me if I have it wrong:

You are registering the object types with your `scheme.Scheme`, but there is nothing telling the (test) apiserver about the CRD itself. kubebuilder bootstraps a snippet that loads the CRDs you are defining and testing directly:

https://github.com/IBM/starter-kit-operator/blob/adffbc16c42d9d899432c67cd9c1e63a27729104/controllers/suite_test.go#L92-L94 

But there is nothing to define the rest of those types with the apiserver (registering Go types with your scheme does not install the associated CRD, it's only telling your local client how to handle that type of object).

For this to work the way you are expecting I think you would need to include the CRDs and add them to that list - otherwise the test apiserver will always return an error when you send a request for a type it hasn't heard of.

Hope that helps.

**Comment by hfgbarrigas** [comment]
Any updates on this? Getting the same error. Using go mod vendor won't help because non go files are pruned.

Apart from crd paths, the environment has an attibute CRDs that looks promising but having issues using it since I can't find any documentation around it . Maybe @camilamacedo86 can shed some light?

**Comment by hfgbarrigas** [comment]
For those running into this, here's how to properly add the external crd manifests to envtest:

```golang
CRDDirectoryPaths: []string{
			filepath.Join("../..", "config", "base", "crd", "bases"),
			filepath.Join(build.Default.GOPATH, "pkg", "mod", "github.com", "owner", "theirs@version", "config", "base", "crd", "bases"),
		},
```

**Comment by camilamacedo86** [comment]
Hi @hfgbarrigas, 

Just to confirm. We can close this one since the error here was solved. by adding the correct path for the CRDs. Am I right?

**Comment by hfgbarrigas** [comment]
Hi @camilamacedo86,

I'd be inclined to close it. Though some documentation on how to do it and why using go modules would nice for future reference.

**Comment by estroz** [comment]
This would be a nice FAQ entry.

**Comment by avrahams** [comment]
> ```go
> crd
> ```
@camilamacedo86 
Will this resolve my issue in the sdk ?
https://github.com/operator-framework/operator-sdk/issues/4434

Where can I find OpenShift Route CRD?

**Comment by mpreu** [comment]
@avrahams 
There is none for `Routes`. All OCP related CRDs are potentially to be found in the [API repo](https://github.com/openshift/api), but a lot of "older" OCP resources are not published that way. Recently had contact with some Red Hat people about that and my information so far is, there is no really immediate plan to change that.

There is a manual way though. One has to create a 'fake' CRD within the correct OCP API repository path and adapt the make targets.

E.g. for `Routes`, a CRD file `route_crd.yaml` with the following content has to be created in the path https://github.com/openshift/api/tree/master/route/v1:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: routes.route.openshift.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: route.openshift.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  subresources:
    # enable spec/status
    status: {}
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: routes
    # singular name to be used as an alias on the CLI and for display
    singular: route
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Route
```

Then the `Makefile` has to get this line:

```bash
$(call add-crd-gen,route,./route/v1,./route/v1,./route/v1)
```

Updating the CRDs with

```bash
make update-codegen-crds
```
populates the CRD stub with the correct OpenAPI validation content.

Unfortunately it seems to only works this way, as the API repo infrastructure already expects the basic CRD to be there (I am sure one can workaround that somehow). 

It works for other resources as well, but it is obviously not a very practical solution. So this is just a documentation comment for people experiencing similar problems with OCP related resources.

Just as a warning: In some of my tests I experienced validation errors populating `envtest` with these CRDs, but I did not investigate it further.
