### ISSUE TITLE
Add old object for webhook Defaulter interface

### ISSUE THREAD

**Issue by scuzhanglei** [kubernetes-sigs/controller-runtime#1328]
admission [Defaulter interface](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/webhook/admission/defaulter.go) like this:
```
// Defaulter defines functions for setting defaults on resources
type Defaulter interface {
	runtime.Object
	Default()
}
```
it does not include old object, sometimes need get the old value from the old object. of course, we can get the old object from apiserver with a client, but this would introduce unnecessary overhead.

we can change the interface to this, if it is acceptable, I can submit a PR.

```
type Defaulter interface {
	runtime.Object
	Default(old runtime.Object)
}
```

**Comment by coderanger** [comment]
You can get the old values from the self pointer, it's filled in for you with whatever the object is. See https://github.com/coderanger/rabbitmq-operator/blob/main/api/v1beta1/rabbitvhost_webhook.go#L39-L41 for an example.

**Comment by scuzhanglei** [comment]
@coderanger thanks, for some reason, sometimes we can't get old value from the object.
for example I have a VM CRD, the VM has a field `macAddress`, the defaulter webhook would generate a new macAddress if it is not specifield in the yaml file, like below:

1. kubectl apply -f vm.yaml
``` yaml
# vm.yaml
apiVersion: xxx.io/v1
kind: VirtualMachine
metadata:
  name: centos
spec:
  newworkInterfaces:
  - name: eth0
    macAddress: 
```
2. the default webhook would generate a macAddress,after webhook handled the VM resource is:

 ```
apiVersion: xxx.io/v1
kind: VirtualMachine
metadata:
  name: centos
spec:
  networkInterfaces:
  - name: eth0
     macAddress: 00:01:02:03:04:05
```

3. kubectl apply -f vm.yaml again. cause in vm.yaml, the macAddress is still empty.  in the webhook the new vm object's `macAddress` is empty not `00:01:02:03:04:05`. this is caused by CRD resource don't support:
```
      // +patchMergeKey=name
	// +patchStrategy=merge
```
related k8s issue [53558](https://github.com/kubernetes/kubernetes/pull/53558).

this is the problem I faced now, of course, it is a problem of k8s CRD not controller-runtime. update the Defaulter interface is a workaround, and maybe there are other situation need this too.
