### ISSUE TITLE
Coupling lifecycle management of CRDs with their manager

### ISSUE THREAD

**Issue by muvaf** [kubernetes-sigs/controller-runtime#1417]
Hi folks!

We have recently [implemented](https://github.com/crossplane/crossplane/pull/2160) a feature in Crossplane that enables the manager executable to deploy the CRDs it's managing before starting. Since Crossplane already has the `ClusterRole` to manage CRDs in the cluster, we didn't need extra privileges. It's done mainly because of upgrade issues experienced with Helm but I think it could be viable to do for all controllers. The problems this approach would solve (or help to solve more easily):
* No need for serial steps for upgrade, i.e. first apply CRDs and then `Deployment` of the controllers.
* Rollback of the controller upgrade; earlier version of the controller would redeploy its CRD.
* Keeping the CRDs that are used by more than one controller instance in sync, i.e. namespaced CRDs with a controller in each namespace; all controllers need to be able to reconcile but if you install an older CRD, schema could be dropped.

I imagine the following structure in `kubebuilder` and `controller-runtime` would work well but I'm curious to hear other folks:
* `kubebuilder` generates a `ClusterRole` for every `CustomResourceDefinition` it generates. It would be specific to that `CustomResourceDefinition` instance and has all verbs except `DELETE`.
* The CRD YAMLs would be copied over to the container image of the controller during build.
* Manager would scan the specific CRDs folder and apply them before starting with the following condition:
  * If the value of the annotation `kubebuilder.io/controller-version` of the local CRD YAML is higher than the one applied in the cluster so that only the latest CRD can ever be applied. Note that `controller-version` is SemVer of the controller; not `apiVersion`. This is due to not lose non-breaking additional changes that are made in the same `apiVersion`.

I'm curious of what you think. I'd be happy to contribute this feature if you think it's feasible.

**Comment by coderanger** [comment]
The reason most operators have stayed away from this is the lack of security isolation. Even just with create and update, access to CRDs can be a major security issue. There is some future where the new service account token APIs would allow running only the initContainer with the needed perms but the basics of the service account system don't allow for that.

**Comment by muvaf** [comment]
>Even just with create and update, access to CRDs can be a major security issue.

Could you elaborate on that? I was thinking an aggregated `ClusterRole` like the following would be contained enough:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acmecontroller-crd
  labels:
    rbac.example.com/aggregate-to-acmecontroller: "true"
rules:
- apiGroups:
  - "apiextensions"
  resources:
  - "customresourcedefinitions"
  resourceNames:
  - "acmekinds.example.com" # the name of the CRD that acmecontroller manages
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "patch"
  - "update"
```

**Comment by coderanger** [comment]
@muvaf Unfortunately there's not a lot of validation on CRDs. The object name has to match plural+group but collisions are allowed on short names, singular names, etc. So just being able to update a CRD could allow all kinds of weird attacks to extract data that shouldn't be accessible. You might already consider someone getting an RCE in Crossplane to be a "game over" scenario, so gameover+1 isn't really a problem for you, but that's not true of most operators :)

**Comment by muvaf** [comment]
> The object name has to match plural+group but collisions are allowed on short names, singular names, etc. So just being able to update a CRD could allow all kinds of weird attacks to extract data that shouldn't be accessible.

Hmm let's say I have permissions on `acmekinds.example.com` CRD and its short name is `ac`. And there is another CRD named `anotherkinds.anotherexample.com` whose short name is `ak`. Do you mean that if I change the short name of `acmekinds.example.com` (`ac`) to `ak`, it'd mean that I now have access to the instances of `anotherkind.anotherexample.com`?

Wanted to test this scenario in a v1.18.2 kind cluster by creating the following YAML:
<details>

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: myuserclusterrole
rules:
- apiGroups: ["example.com"]
  resources: ["acmekinds"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: myuserclusterrolebinding
subjects:
- kind: ServiceAccount
  name: myuser
  namespace: default
roleRef:
  kind: ClusterRole
  name: myuserclusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myuser
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: acmekinds.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
  scope: Namespaced
  names:
    plural: acmekinds
    singular: acmekind
    kind: AcmeKind
    shortNames:
    - ac
---
apiVersion: example.com/v1
kind: AcmeKind
metadata:
  name: acmekind-1
  namespace: default
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: anotherkinds.anotherexample.com
spec:
  group: anotherexample.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
  scope: Namespaced
  names:
    plural: anotherkinds
    singular: anotherkind
    kind: AnotherKind
    shortNames:
    - ak
---
apiVersion: anotherexample.com/v1
kind: AnotherKind
metadata:
  name: anotherkind-1
  namespace: default
```

</details>

When I'm using kubeconfig of `ServiceAccount` named `myuser`, I get the following outputs as expected:
```bash
$ kubectl auth can-i get ac
yes
$ kubectl get ac
NAME         AGE
acmekind-1   3m48s
$ kubectl auth can-i get ak
no
$ kubectl get ak
Error from server (Forbidden): anotherkinds.anotherexample.com is forbidden: User "system:serviceaccount:default:myuser" cannot list resource "anotherkinds" in API group "anotherexample.com" in the namespace "default"
```

Then I change `shortName` of `acmekinds.example.com` to `ak` by applying the following:
<details>

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: acmekinds.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
  scope: Namespaced
  names:
    plural: acmekinds
    singular: acmekind
    kind: AcmeKind
    shortNames:
    - ak
```

</details>

Then when I try to get `AnotherKind` through `ak` short name, I get the following:
```bash
$ kubectl auth can-i get ak
no
$ kubectl get ak
Error from server (Forbidden): anotherkinds.anotherexample.com is forbidden: User "system:serviceaccount:default:myuser" cannot list resource "anotherkinds" in API group "anotherexample.com" in the namespace "default"
```

`kubectl get ak` returns `anotherkind-1` when run by the admin. Then I changed short name of `AnotherKind` to `ac` and run the following commands with the `myuser` SA:
```
$ kubectl auth can-i get ak
yes
$ kubectl auth can-i get ac
no
```

Though note that when the short name is changed, I had to open a new tab for kubectl to not use the cached kind+group name corresponding to the short names, because I think once it does the discovery it saves that information in the session. Nevertheless, in all cases I see that the final actual `GET` request includes the kind and group:
```
GET https://127.0.0.1:51442/apis/anotherexample.com/v1/namespaces/default/anotherkinds?limit=500
```

So from what I can tell, short name is used only for discovery and the final calls are made with full kind and group meaning having the ability to change short or singular name doesn't really affect the ability to fetch because actual call has to include plural+group.
