### ISSUE TITLE
unable to read CacheSyncTimeout from config.yaml

### ISSUE THREAD

**Issue by aagu** [kubernetes-sigs/controller-runtime#1840]
My controller exit with panic like this:
```
panic: could not parse config file: could not decode file into runtime.Object
``` 
The cause is due to 'wrong' configuration be provided:
```
# config.yaml
apiVersion: config.somedomain.io/v1alpha1
kind: FoobarControllerManagerConfiguration
spec:
  port: 9443
  metricsBindAddress: ":8080"
  leaderElection:
    leaderElect: false
  controller:
    cacheSyncTimeout: '30s'
```
The CacheSyncTimeout defined at [ControllerConfigurationSpec](https://github.com/kubernetes-sigs/controller-runtime/blob/e42a8c17945360813e64bde2c4ff742515b750ba/pkg/config/v1alpha1/types.go#L96) has type time.Duration, which is different from the type of SyncPeriod defined at outer struct [ControllerManagerConfigurationSpec](https://github.com/kubernetes-sigs/controller-runtime/blob/e42a8c17945360813e64bde2c4ff742515b750ba/pkg/config/v1alpha1/types.go#L36).
The time.Duration type is an alias for int64 and thus cannot be read from string format in json or yaml.
We may need to change the type of CacheSyncTimeout to metav1.Duration to keep consistent with outer SyncPeriod?
