### ISSUE TITLE
TypeMeta : Kind + ApiVersion are empty when the object is processed the first time

### ISSUE THREAD

**Issue by cmoulliard** [kubernetes-sigs/controller-runtime#202]
## Bug

Original ticket : https://github.com/operator-framework/operator-sdk/issues/727

When I create a `Component`'s custom resource, the component is well created and the MetaData well defined (Kind, ApiVersion)

```
oc get cp/fruit-client -o yaml                
apiVersion: component.k8s.io/v1alpha1
kind: Component
metadata:
  name: fruit-client
  namespace: my-spring-app
spec:
  deployment: innerloop
  exposeService: true
  runtime: springboot
  version: 1.5.16
```

but when the reconcile's function of the controller fetch the Component, then the Kind, ApiVersion fields are empty

What is the root cause of this issue ?

![screenshot 2018-11-09 12 27 43](https://user-images.githubusercontent.com/463790/48260329-53718a80-e41b-11e8-8696-f42ed333a9d1.png)

## Environment

```
okd : 3.11 (= kubernetes v1.11)
operator-sdk : v0.1.1+git
```

## Project

Code of the API : https://github.com/snowdrop/component-operator/tree/operator-0.1.1/pkg/apis
Code of the controller : https://github.com/snowdrop/component-operator/blob/operator-0.1.1/pkg/controller/component/handler.go#L94

## Hypothesis

As described [here](https://github.com/operator-framework/operator-sdk/issues/727#issuecomment-437343992) I suspect that we have a `deepCopy` issue the first time that we get the object from the cache
