### ISSUE TITLE
Fake client refuses to initialize with the objects that have deletionTimestamp set but no finalizers

### ISSUE THREAD

**Issue by arkbriar** [kubernetes-sigs/controller-runtime#2359]
If you try to create a fake client with the following code,

```go
func TestControllerReconcileWhenObjectDeleted(t *testing.T) {
        client := fake.NewClientBuilder().WithObjects(&corev1.Pod{
                ObjectMeta: metav1.ObjectMeta{
			Name:              "example",
			Namespace:         "default",
			DeletionTimestamp: &metav1.Time{Time: time.Now()},
		},
        }).Build()
}
```

the test will fail because

> refusing to create obj example with metadata.deletionTimestamp but no finalizers

That makes no sense. These objects can just exist and the controllers should behave correctly in such cases. The restriction prevents us from simulating such a case with the fake client.

The issue was introduced in https://github.com/kubernetes-sigs/controller-runtime/commit/7a66d580c0c53504f5b509b45e9300cc18a1cc30.

**Comment by alvaroaleman** [comment]
It does make sense, because deletiontimestamp-without-a-finalizer is a state you won't be able to observe in a real kube-apiserver either

**Comment by arkbriar** [comment]
> It does make sense, because deletiontimestamp-without-a-finalizer is a state you won't be able to observe in a real kube-apiserver either

I don't think so. Actually, you can simply get such an object by
1. Apply the Pod below and wait until it starts
2. Delete it

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: d
spec:
  terminationGracePeriodSeconds: 600
  containers:
  - name: d
    image: busybox:latest
    command:
    - sh
    args:
    - -c
    - while :; do sleep 1000; done
    lifecycle:
      preStop:
        exec:
          command: ["sleep", "10000"]
```

Here's an example:

```plain
$ k get pod d -o jsonpath='{"deletionTimestamp: "}{.metadata.deletionTimestamp}{"\nfinalizers: "}{.metadata.finalizers}'
deletionTimestamp: 2023-05-29T10:06:45Z
finalizers:
```

In fact, deletion in Kubernetes is just an alias of setting the deletionTimestamp to an non-zero value. It doesn't mean that the object will be delete immediately.
