### ISSUE TITLE
Enable adding and removing watches at runtime.

### ISSUE THREAD

**Issue by nkvoll** [kubernetes-sigs/controller-runtime#246]
It would be great if there was a way to add and remove watches during the controller lifecycle.

Use case: want to be able to get some data from a user-supplied secret, instead of inline:
```yaml
    credentials:
        secretSource:
            name: name-of-a-secret-containing-some-credentials
        #inline:
        #    username: foo
        #    password: bar
```
- If `secretSource` is specified, we want to add a watch for it so we can reconcile when it changes (likely have to provide a custom `handler.EventHandler` to reconcile the correct object(s)).
- If it is no longer specified, we want to remove the watch for it (if we created it) so we no longer spend resources on having an unused watch.
- This means the resources we would like to have watches for may change over time, so the ability to not only add, but also remove watches becomes important.
