### ISSUE TITLE
Enhancement of Authentication and Authorization Filters to Allow Custom Configurations and Stability Improvements

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/controller-runtime#2781]
## Enhancement Proposal: Authentication and Authorization Filters

**Context**: Following the implementation introduced in [PR #2407](https://github.com/kubernetes-sigs/controller-runtime/pull/2407), several issues regarding configurability and robustness were identified.

### Issues Identified
- **Configurability**: Current settings such as cache TTL, timeouts, and anonymous access are hardcoded and cannot be adjusted.
- **Certificate Authentication**: The implementation disrupts normal certificate authentication processes.
- **Authorization Flexibility**: Lack of support for `alwaysAllow` configurations for critical paths like `/healthz` and `alwaysAllowGroups` like `system:masters`.
- **Network Resilience**: Heavy dependency on stable connectivity to kube-apiserver can lead to metrics outages under network instability.

### Proposed Changes

Enhance the filters by introducing configurations for previously hardcoded settings, and by allowing the injection of custom authorizers, similar to the approach in [kube-rbac-proxy PR #43](https://github.com/openshift/kube-rbac-proxy/pull/43).

### Impact

These changes would enhance the flexibility and reliability of the authentication and authorization processes in controller-runtime, aligning with the needs of robust Kubernetes deployments.

c/c @deads2k @sbueringer

**Comment by camilamacedo86** [comment]
HI @deads2k,

First of all, thank you very much for your assistance with this issue. Your expertise and deep knowledge are invaluable here, and I/and the community for sure greatly appreciate your involvement. Please feel free to add any additional insights or correct any points I might have missed or misunderstood.

**Comment by sbueringer** [comment]
Thx for opening this issue and the feedback. In general makes sense to improve the feature where necessary.

One question. Are the issues identified above from the kube-rbac-proxy audit or from the current implementation in controller-runtime? (I'm not sure if they all apply in CR, as we only implement a subset of the kube-rbac-features)

**Comment by camilamacedo86** [comment]
Hi @sbueringer,

IHMO all seems to apply because the feedback here in my understand is mainly keep the things configurable for properly inform the certs. Regards the `Lack of support for alwaysAllow configurations for critical paths like /healthz and alwaysAllowGroups like system:masters.`  it seems that it could appear to work, but then cause metrics outages when networking to the kube-apiserver is flaky, which is one of the most important times to have metrics.

**Comment by camilamacedo86** [comment]
hi @sbueringer 

Could we frozen this one?
Until someone be able to look on it and see if can address the enhancements?

**Comment by mrueg** [comment]
It would be nice if we could have also resource-attribute based authorization in the filter, similar to: https://github.com/brancz/kube-rbac-proxy/tree/master/examples/resource-attributes

I believe this would allow more fine grained access than the non-resource URL approach

**Comment by sbueringer** [comment]
If I'm not mistaken filters.WithAuthenticationAndAuthorization is only used to protect the metrics endpoint.

Can you please give an example how that feature would improve the authentication/authorization of the metrics endpoint?

**Comment by mrueg** [comment]
As far as I know, NonResourceURL's are not namespaced, so using a NRU means I give access to all /metrics endpoints int he cluster.

I was hoping that SubResources are namespacable, so we could do:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metrics-reader
  namespace: application-namespace
rules:
- apiGroups: [""]
  resources: ["services/proxy"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-reader
  namespace: application-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-rbac-proxy-client
subjects:
- kind: ServiceAccount
  name: metrics-fetcher
  namespace: default
```
