### ISSUE TITLE
Using leader election with webhook manager

### ISSUE THREAD

**Issue by SchSeba** [kubernetes-sigs/controller-runtime#356]
When we create a manager with leader election and a webhook only one manager start but looking into the service the manger creates for the webhook he add all the pod.

Proposed solution:

Use the label statefulset.kubernetes.io/pod-name=<podname> for the webhook service and when the election change update the service label(or recreate the service)

More general solution can be to have a general label like `controller-leader` and just update the leader pod with this label.

**Comment by DirectXMan12** [comment]
So, we shouldn't do that, since webhooks support active-active HA quite easily.  It should be possible to start the webhook server *without* starting the controllers.  For that we probably need the concept of things which are active-passive vs active-active. 

@mengqiy FYI

**Comment by DirectXMan12** [comment]
/kind bug
/priority important-soon

This is something we intended to work properly, but doesn't, so I'm treating it as a bug here.

**Comment by pytimer** [comment]
@DirectXMan12 I have the problem similar to @SchSeba said, but i use `Deployment` to deploy manager in Kubernetes cluster. I add a `readinessProbe` in manager yaml, below is my yaml:

```yaml
name: manager
readinessProbe:
  tcpSocket:
    port: 9876
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 2
```

This's works ok for me, but i see manager have the `http: TLS handshake error from 10.244.3.1:47680: EOF` log every 10 seconds, so i want to use `httpGet` instead of `tcpSocket`, but i have no idea how to setting.
