### ISSUE TITLE
Cannot define a field with arbitrary structure

### ISSUE THREAD

**Issue by nicolaferraro** [kubernetes-sigs/controller-runtime#628]
I'm trying to define a controller for a type with some unknown parts in the tree that can contain arbitrary structures.

E.g.

```
apiVersion: my.dev/v1alpha1
kind: TypeWithSemistructuredData
metadata:
  name: thename
spec:
  replicas: 1
  myUnknownField:
    structure:
      ofThis:
        - isUnknown: true
      butStill:
        - yaml
        - json
        - compatible
```

Problem is how to map `myUnknownField` into an actual struct field. I've tried:

- `map[interface{}]interface{}`: controller runtime fails because cannot map `interface{}`
- `runtime.Unknown`: it's always nil
- `runtime.RawExtension`: ... well, it's a snippet, not a `runtime.Object`

Is there a clean way to define such fields that can contain objects with arbitrary structure?
